sudo: required
language: python
group: deprecated-2017Q4
notifications:
  email:
    - ci@sensenet.ai
python:
  - 3.6
services:
  - docker
before_install:
  - sudo sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-precise main" > /etc/apt/sources.list.d/docker.list'
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - sudo apt-get update
  - sudo apt-key update
  - sudo apt-get --force-yes -qqy -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install docker-engine=1.11.1-0~precise
  - sudo add-apt-repository  ppa:mc3man/trusty-media -y
  - sudo apt-get update
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.7.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose -v
  - docker -v
install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements_test.txt
script:
  - cd tests && pytest

